meta:
  author: 'tyx'


train:
  seed: 10
  debug: false #True
  # optimizer
  optimizer: 'adamw'
  lr: 0.001
  grad_norm_clip: 1.0

  # dataloader
  batch_size: 128

  # loop control
  max_epoch: 100

checkpoint:
  save_ckpt: True
  ckpt_dir: './tmp'
  ckpt_interval: 10

logging:
  output_dir: './tmp'