meta:
  author: "tyx"

train:
  device: "cuda:0"
  seed: 30

  # optimization
  lr_warmup_steps: 20
  num_epochs: 500

  # training loop control in epochs
  validation_every: 10
  test_every: 10

optimizer:
  lr: 1.0e-4
  betas: [0.95, 0.999]
  eps: 1.0e-8
  weight_decay: 1.0e-5

train_dataloader:
  data_dir: ['/home/yxtang/CodeBase/PythonCourse/PythonRobotics/PathPlanning/st_dlo_planning/results/gdm_mj/train',]
  batch_size: 256
  num_workers: 1
  shuffle: True
  pin_memory: True
  persistent_workers: False

val_dataloader:
  batch_size: 256
  num_workers: 1
  shuffle: True
  pin_memory: True
  persistent_workers: False

test_dataloader:
  data_dir: ['/home/yxtang/CodeBase/PythonCourse/PythonRobotics/PathPlanning/st_dlo_planning/results/gdm_mj/test',]
  batch_size: 256
  num_workers: 1
  shuffle: False
  pin_memory: True
  persistent_workers: False

logging:
  mode: "online"
  wandb_project: "st_dlo_project"
  experiment_name: "st_dlo_gdm"
  output_dir: "/home/yxtang/CodeBase/PythonCourse/PythonRobotics/PathPlanning/st_dlo_planning/outputs"
  ckpt_dir: "/home/yxtang/CodeBase/PythonCourse/PythonRobotics/PathPlanning/st_dlo_planning/results"

checkpoint:
  save_checkpoint: True
  checkpoint_every: 20
  ckpt_dir: '${logging.ckpt_dir}/checkpoints/${logging.experiment_name}_${train.seed}'
  save_last_ckpt: True
