meta:
  author: tyx
model:
  inp_dim: 1
  out_dim: 1
train:
  seed: 10
  debug: false
  optimizer: adamw
  lr: 0.001
  grad_norm_clip: 1.0
  batch_size: 128
  max_epoch: 100
checkpoint:
  save_ckpt: true
  ckpt_dir: ./tmp
  ckpt_interval: 10
logging:
  output_dir: ./tmp
