meta:
  author: 'tyx'

model:
  inp_dim: 1
  out_dim: 1

train:
  seed: 0
  debug: false #True
  # optimizer
  optimizer: 'adamw'
  lr: 0.001
  grad_norm_clip: 1.0

  # dataloader
  batch_size: 128

  # loop control
  max_epoch: 50

checkpoint:
  save_ckpt: True
  ckpt_dir: './tmp'

logging:
  output_dir: './tmp'